# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fd4f19dfd405c3f39fffe220f2ba9826d3f54d2b68f9cb6a32d9182d3853df2c18c0300b94e9430f2e538a9b15f5ef5a5b7fd1c05324b268989f28d2b2e2e0e2

test:
  secret_key_base: 801c2eee8446c6993a72fe17d3b0c598ce2d1bed9dd745801e92e3cd8a19b8a53b6c33e6a23ab52b4e8904a6a0d671959a3a79471c06986d67e1e00ec7baf677

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
